service: my-typescript-express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-east-1

functions:
  app:
    handler: build/index.handler # point to the compiled JavaScript file
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
  setup:
    handler: build/index.handler # point to the compiled JavaScript file
    timeout: 500 # in seconds
    events:
      - http:
          path: /setup
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - build/** # include compiled files
  exclude:
    - node_modules/** # exclude all node_modules
    - src/** # exclude TypeScript source files
