name: Dev Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: npm install

      - name: Serverless Deploy
        run: npx serverless deploy --stage dev --verbose --config serverless-dev.yml
        env:
          MONGODB_URI: ${secrets.MONGODB_URI}
          NITRO_ENDPOINT: ${secrets.NITRO_ENDPOINT}
          MIRROR_ENDPOINT: ${secrets.MIRROR_ENDPOINT}
          TOKENS_DATA_ENDPOINT: ${secrets.TOKENS_DATA_ENDPOINT}
          TOKENS_PRICE_ENDPOINT: ${secrets.TOKENS_PRICE_ENDPOINT}
          GRAPHQL_TOKEN_ENDPOINT: ${secrets.GRAPHQL_TOKEN_ENDPOINT}
          RPC_ENDPOINT: ${secrets.RPC_ENDPOINT}
          DISCORD_WEBHOOK: ${secrets.DISCORD_WEBHOOK}
          SERVERLESS_ACCESS_KEY: ${secrets.SERVERLESS_ACCESS_KEY}
